### ISSUE TITLE
在 MacOS 上安装 Kafka

### ISSUE THREAD

**Issue by smallnest** [smallnest/gitalk#147]
https://colobu.com/2019/09/27/install-Kafka-on-Mac/

**Comment by laob9444** [comment]
带账号密码的远程端怎么连？

**Comment by SeekPoint** [comment]
% kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test
Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:262)
	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:258)
	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:119)
	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1863)
	at kafka.admin.TopicCommand$ZookeeperTopicService$.apply(TopicCommand.scala:341)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:55)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)

**Comment by Andy-Geng** [comment]
> @loveJasmine
> % kafka-topics --create --zookeeper localhost:2181 --replication-factor 1 --partitions 1 --topic test
> Exception in thread "main" kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
> 	at kafka.zookeeper.ZooKeeperClient.$anonfun$waitUntilConnected$3(ZooKeeperClient.scala:262)
> 	at kafka.zookeeper.ZooKeeperClient.waitUntilConnected(ZooKeeperClient.scala:258)
> 	at kafka.zookeeper.ZooKeeperClient.<init>(ZooKeeperClient.scala:119)
> 	at kafka.zk.KafkaZkClient$.apply(KafkaZkClient.scala:1863)
> 	at kafka.admin.TopicCommand$ZookeeperTopicService$.apply(TopicCommand.scala:341)
> 	at kafka.admin.TopicCommand$.main(TopicCommand.scala:55)
> 	at kafka.admin.TopicCommand.main(TopicCommand.scala)
> 

用卡夫卡自带的zookeeper就可以了，别单独装了

**Comment by a123zyy** [comment]
不用下载zk 也不用注释注释 下载下来运行就行

**Comment by RunDouble** [comment]
新 macOS，homebrew 安装的软件，配置文件路径：/opt/homebrew/etc/

如 kafka 配置文件位置：/opt/homebrew/etc/kafka
